export const DATA = [
  {
    id: "1",
    videoId: "wwapBsT0oc8",
    title: "Adobo",
    image: require("./img/adobo.jpeg"),
    ingredients: [
      "2 tablespoons vegetable oil",
      "1/2 kg pork, cut into pieces",
      "1 onion, chopped",
      "1 head garlic, minced",
      "1/2 cup soy sauce",
      "1/4 cup vinegar",
      "1 tablespoon sugar",
      "1 tablespoon cooking oil",
      "1/2 cup water",
      "Bay leaves",
    ],
    cookingTime: 45,
    originCountry: "Philippines",
    difficulty: "Easy",
    procedure: [
      "1. In a pan, sauté chopped onion and minced garlic in cooking oil.",
      "2. Add chicken and pork, cook until golden brown.",
      "3. Pour in soy sauce, vinegar, sugar, and water. Simmer until meat is cooked.",
      "4. Add bay leaves and simmer for a few more minutes.",
      "5. Serve hot with rice. Enjoy your Chicken and Pork Adobo!",
    ],
    imageBackground: require("./img/philippines.jpg")
  },

  {
    id: "2",
    videoId: "CzBF1IhIn1M",
    title: "Sinigang",
    image: require("./img/sinigang.jpeg"),
    ingredients: [
      "1/2 kg pork, cut into pieces",
      "1 cup tamarind pulp",
      "1 radish, sliced",
      "1 eggplant, sliced",
      "1 long green chili pepper",
      "2 onions, sliced",
      "2 liters water",
      "1 packet sinigang mix",
      "Salt and pepper to taste",
    ],
    cookingTime: 60,
    originCountry: "Philippines",
    difficulty: "Intermediate",
    procedure: [
      "1. Boil water in a pot.",
      "2. Add pork pieces and cook until tender.",
      "3. Add vegetables like radish, eggplant, onions, and green chili pepper.",
      "4. Mix in tamarind pulp and sinigang mix. Simmer until vegetables are cooked.",
      "5. Season with salt and pepper according to taste.",
      "6. Serve hot. Enjoy your Pork Sinigang!",
    ],
    imageBackground: require("./img/philippines.jpg")
  },
  {
    id: "3",
    videoId: "M-Gso2xK9t8",
    title: "Sisig",
    image: require("./img/sisig.jpeg"),
    ingredients: [
      "1/2 kg pork face, boiled and grilled, then finely chopped",
      "1/4 kg pork liver, boiled and grilled, then finely chopped",
      "1 onion, minced",
      "3 cloves garlic, minced",
      "3 to 4 pieces red and green chili peppers, minced",
      "1 tablespoon soy sauce",
      "1 tablespoon calamansi juice",
      "Salt and pepper to taste",
      "Mayonnaise for topping",
      "1 egg (optional), sunny side up",
    ],
    cookingTime: 45,
    originCountry: "Philippines",
    difficulty: "Easy",
    procedure: [
      "1. Boil pork face and liver until tender. Grill until cooked, then finely chop.",
      "2. In a pan, sauté minced onion and garlic until fragrant.",
      "3. Add the chopped pork face and liver to the pan. Cook until slightly crispy.",
      "4. Mix in soy sauce, calamansi juice, and minced chili peppers. Stir well.",
      "5. Season with salt and pepper according to taste.",
      "6. Top with mayonnaise and, if desired, a sunny side up egg.",
      "7. Serve hot. Enjoy your Sisig!",
    ],
    imageBackground: require("./img/philippines.jpg")
  },
  {
    id: "4",
    videoId: "KnJ3abXjgME",
    title: "Peking Duck",
    image: require("./img/pekingduck.jpeg"),
    ingredients: [
      "1 whole duck (about 5-6 lbs)",
      "1/4 cup honey",
      "1/4 cup soy sauce",
      "2 tablespoons hoisin sauce",
      "1 tablespoon rice vinegar",
      "1 teaspoon Chinese five-spice powder",
      "4 cups hot water",
      "1 cup maltose syrup or corn syrup",
      "Air compressor or a hand pump for inflating the skin",
      "Thin pancakes or steamed buns, for serving",
      "Sliced green onions and cucumber strips, for garnish",
      "Hoisin sauce, for dipping",
    ],
    cookingTime: 120,
    originCountry: "China",
    difficulty: "Advanced",
    procedure: [
      "1. Clean and pat dry the duck. In a small saucepan, combine honey, soy sauce, hoisin sauce, rice vinegar, and Chinese five-spice powder. Heat until well combined.",
      "2. Brush the duck inside and out with the sauce. Hang the duck in a cool, dry place for at least 24 hours to air-dry the skin.",
      "3. Preheat the oven to 350°F (180°C). In a pot, bring 4 cups of hot water to a boil. Pour the hot water over the duck to tighten the skin.",
      "4. Mix maltose syrup or corn syrup with water to thin it out. Brush the duck with the syrup mixture, ensuring an even coating.",
      "5. Inflate the duck skin by blowing air between the skin and meat. Hang the duck again for another 4-6 hours until the skin is dry and tight.",
      "6. Preheat the oven to 350°F (180°C). Roast the duck for about 1.5 to 2 hours or until the skin is crispy and the internal temperature reaches 165°F (74°C).",
      "7. Let the duck rest for a few minutes before carving. Serve the Peking Duck with thin pancakes or steamed buns, sliced green onions, cucumber strips, and hoisin sauce.",
      "8. To eat, spread hoisin sauce on a pancake or bun, add slices of duck, green onions, and cucumber. Roll it up and enjoy!",
    ],
    imageBackground: require("./img/china.jpg")
  },
  {
    id: "5",
    videoId: "mQufT9XjimY",
    title: "Kung Pao Chicken",
    image: require("./img/kungpaochicken.jpg"),
    ingredients: [
      "1 lb boneless, skinless chicken breasts, cut into bite-sized pieces",
      "1/2 cup unsalted dry roasted peanuts",
      "2 tablespoons vegetable oil",
      "3 cloves garlic, minced",
      "1 teaspoon ginger, minced",
      "2 tablespoons soy sauce",
      "1 tablespoon rice vinegar",
      "1 tablespoon hoisin sauce",
      "1 tablespoon sugar",
      "1 teaspoon cornstarch",
      "1/2 cup chicken broth",
      "2 green onions, sliced",
      "1 red bell pepper, diced",
      "2 dried red chili peppers",
      "Cooked rice, for serving",
    ],
    cookingTime: 30,
    originCountry: "China",
    difficulty: "Intermediate",
    procedure: [
      "1. In a small bowl, mix together soy sauce, rice vinegar, hoisin sauce, sugar, cornstarch, and chicken broth to create the sauce. Set aside.",
      "2. Heat vegetable oil in a wok or large skillet over medium-high heat. Add chicken pieces and stir-fry until browned and cooked through. Remove chicken from the pan and set aside.",
      "3. In the same pan, add a bit more oil if needed. Sauté garlic, ginger, and dried red chili peppers until fragrant.",
      "4. Add diced red bell pepper and stir-fry for a couple of minutes until slightly softened.",
      "5. Return the cooked chicken to the pan. Pour in the sauce and mix well. Allow the sauce to thicken.",
      "6. Add peanuts and sliced green onions. Stir until everything is evenly coated and heated through.",
      "7. Serve over cooked rice. Enjoy your Kung Pao Chicken!",
    ],
    imageBackground: require("./img/china.jpg")
  },
  {
    id: "6",
    videoId: "34Ax3BmGtY0",
    title: "Dumplings",
    image: require("./img/dumpling.jpeg"),
    ingredients: [
      "1 lb ground pork",
      "2 cups Napa cabbage, finely chopped",
      "3 green onions, finely chopped",
      "2 tablespoons soy sauce",
      "1 tablespoon sesame oil",
      "1 tablespoon fresh ginger, minced",
      "1 clove garlic, minced",
      "1/2 teaspoon black pepper",
      "1 package round dumpling wrappers",
      "Water for sealing dumplings",
      "Dipping sauce (soy sauce, rice vinegar, and sesame oil)",
    ],
    cookingTime: 45,
    originCountry: "China",
    difficulty: "Easy",
    procedure: [
      "1. In a large bowl, combine ground pork, Napa cabbage, green onions, soy sauce, sesame oil, ginger, garlic, and black pepper. Mix well.",
      "2. Take a dumpling wrapper and place a spoonful of the pork mixture in the center.",
      "3. Moisten the edges of the wrapper with water and fold it in half, pressing the edges to seal the dumpling. You can also create pleats along the edge for a decorative touch.",
      "4. Repeat until all the filling is used. Place the dumplings on a baking sheet lined with parchment paper.",
      "5. Bring a large pot of water to a boil. Carefully add the dumplings to the boiling water and cook until they float to the surface, about 5-7 minutes.",
      "6. Alternatively, you can pan-fry the dumplings for a crispy texture. Heat oil in a pan, place dumplings in the pan, and cook until the bottoms are golden brown.",
      "7. Serve hot with a dipping sauce made from soy sauce, rice vinegar, and sesame oil.",
      "8. Enjoy your delicious homemade Chinese Dumplings!",
    ],
    imageBackground: require("./img/china.jpg")
  },
  {
    id: "7",
    videoId: "TgoN7bsTFmU",
    title: "Sashimi",
    image: require("./img/sashimi.jpeg"),
    ingredients: [
      "Fresh raw fish (e.g., salmon, tuna)",
      "Soy sauce",
      "Wasabi",
      "Pickled ginger",
    ],
    cookingTime: 15,
    originCountry: "Japan",
    difficulty: "Easy",
    procedure: [
      "1. Start with a fresh sushi-grade salmon fillet. Ensure that it has been properly frozen to eliminate any potential parasites.",
      "2. Using a sharp knife, slice the salmon against the grain into thin slices. The slices should be about 1/4 to 1/2 inch thick.",
      "3. Arrange the salmon slices on a serving plate in a visually appealing manner.",
      "4. Serve with soy sauce on the side for dipping. Add a small amount of wasabi and pickled ginger for extra flavor.",
      "5. Optionally, you can garnish with sliced green onions or sesame seeds for added texture and taste.",
      "6. Enjoy your Salmon Sashimi immediately for the best freshness and flavor.",
    ],
    imageBackground: require("./img/japan.jpg")
  },
  {
    id: "8",
    videoId: "l8BCDXkwHwI",
    title: "Soba",
    image: require("./img/soba.jpeg"),
    ingredients: [
      "8 oz (about 230g) soba noodles",
      "Dipping Sauce:",
      "1/2 cup soy sauce",
      "1/4 cup mirin (sweet rice wine)",
      "1/4 cup dashi (Japanese soup stock)",
      "1 tablespoon sugar",
      "Toppings (optional):",
      "Green onions, finely chopped",
      "Wasabi",
      "Nori (seaweed), shredded",
    ],
    cookingTime: 20,
    originCountry: "Japan",
    difficulty: "Easy",
    procedure: [
      "1. Bring a large pot of water to boil. Cook the soba noodles according to the package instructions (usually about 5-7 minutes).",
      "2. While the noodles are cooking, prepare an ice bath by combining ice and water in a large bowl.",
      "3. Drain the cooked soba noodles and immediately transfer them to the ice bath to cool rapidly. This helps them maintain a firm texture.",
      "4. In a small saucepan, combine soy sauce, mirin, dashi, and sugar. Heat over medium heat until the sugar dissolves. Let the dipping sauce cool.",
      "5. Once the soba noodles are cool, drain them from the ice bath and arrange them on a bamboo or mesh strainer (zaru) to allow excess water to drain off.",
      "6. Serve the soba noodles on individual plates or a large plate for sharing. Optionally, garnish with shredded nori, chopped green onions, and a dollop of wasabi.",
      "7. Dip the soba noodles into the prepared dipping sauce before eating.",
      "8. Enjoy your refreshing Zaru Soba!",
    ],
    imageBackground: require("./img/japan.jpg")
  },
  {
    id: "9",
    videoId: "joweUxpHaqc",
    title: "Sushi",
    image: require("./img/sushi.jpeg"),
    ingredients: [
      "Sushi rice (prepared)",
      "Fresh salmon, sushi-grade",
      "Soy sauce, for dipping",
      "Wasabi and pickled ginger, for serving",
    ],
    cookingTime: 30,
    originCountry: "Japan",
    difficulty: "Easy",
    procedure: [
      "1. Prepare sushi rice and let it cool to room temperature.",
      "2. Cut the sushi-grade salmon into small, rectangular pieces, about 2 inches long and 1 inch wide.",
      "3. Wet your hands with water to prevent the rice from sticking. Take a small amount of sushi rice and form it into an oval-shaped mound.",
      "4. Place a piece of salmon on top of the rice, pressing it slightly to adhere.",
      "5. Repeat the process for as many nigiri pieces as desired.",
      "6. Serve the salmon nigiri with soy sauce on the side for dipping. Add a small amount of wasabi and pickled ginger for extra flavor.",
      "7. Enjoy your Classic Salmon Nigiri!",
    ],
    imageBackground: require("./img/japan.jpg")
  },
  {
    id: "10",
    videoId: "uggcCFhgUSQ",
    title: "Pad thai",
    image: require("./img/pad-thai.jpeg"),
    ingredients: [
      "8 oz rice noodles",
      "2 tablespoons vegetable oil",
      "1 cup firm tofu, cubed",
      "2 cloves garlic, minced",
      "1/2 cup peanuts, chopped",
      "1 cup bean sprouts",
      "2 green onions, chopped",
      "2 eggs, lightly beaten",
      "1 lime, cut into wedges",
      "1/4 cup chopped cilantro",
      "1/4 cup chopped fresh basil",
      "2 tablespoons fish sauce",
      "2 tablespoons soy sauce",
      "1 tablespoon tamarind paste",
      "1 tablespoon sugar",
    ],
    cookingTime: 10,
    difficulty: "Intermediate",
    originCountry: "Thailand",
    procedure: [
      "1. Cook rice noodles according to package instructions; drain and set aside.",
      "2. In a wok or large skillet, heat vegetable oil over medium-high heat.",
      "3. Add tofu and cook until golden brown. Remove from the wok and set aside.",
      "4. In the same wok, add minced garlic and cook until fragrant.",
      "5. Push garlic to one side and pour beaten eggs into the other side. Scramble eggs until just set.",
      "6. Add cooked noodles, tofu, fish sauce, soy sauce, tamarind paste, and sugar to the wok. Toss everything together.",
      "7. Stir in half of the chopped peanuts, bean sprouts, and green onions. Cook for an additional 2-3 minutes.",
      "8. Serve Pad Thai on a platter, garnished with remaining peanuts, chopped cilantro, fresh basil, and lime wedges.",
    ],
    imageBackground: require("./img/thailand.jpg")
  },
  {
    id: "11",
    videoId: "qlKUHFmLsLo",
    title: "Kimchi Fried Rice",
    image: require("./img/kimchirice.jpg"),
    ingredients: [
      "cups cooked rice, chilled",
      "1 cup kimchi, chopped",
      "1/2 cup kimchi juice",
      "1 cup cooked and shredded chicken or pork",
      "1 carrot, diced",
      "1 cup frozen peas",
      "2 eggs, beaten",
      "3 green onions, sliced",
      "2 tablespoons soy sauce",
      "1 tablespoon sesame oil",
    ],
    cookingTime: 15,
    difficulty: "Easy",
    originCountry: "South Korea",
    procedure: [
      "Heat a large skillet or wok over medium heat.",
      "Add diced carrots and cook until slightly softened.",
      "Add kimchi and shredded chicken/pork to the skillet; stir-fry for a few minutes.",
      "Push the ingredients to one side of the skillet; pour beaten eggs into the other side. Scramble eggs until cooked.",
      "Mix everything in the skillet together.",
      "Add chilled rice, kimchi juice, frozen peas, soy sauce, and sesame oil. Stir-fry until well combined and heated through.",
      "Garnish with sliced green onions before serving.",
    ],
    imageBackground: require("./img/southkorea.jpg")
  },
  {
    id: "12",
    videoId: "TLl8n5WJJfI",
    title: "Tom Yum Soup",
    image: require("./img/TomYumSoup.jpeg"),
    ingredients: [
      "4 cups chicken broth",
      "1 stalk lemongrass, sliced",
      "3 kaffir lime leaves",
      "200g shrimp, peeled and deveined",
      "200g mushrooms, sliced",
      "1 medium tomato, cut into wedges",
      "1 small onion, sliced",
      "2 tablespoons fish sauce",
      "1 tablespoon lime juice",
      "1 teaspoon chili paste",
      "Fresh cilantro for garnish",
    ],
    cookingTime: 10,
    difficulty: "Intermediate",
    originCountry: "Thailand",
    procedure: [
      "In a pot, bring chicken broth to a boil. Add lemongrass and kaffir lime leaves.",
      "Add shrimp, mushrooms, tomato, and onion to the pot.",
      "Season with fish sauce, lime juice, and chili paste.",
      "Simmer until shrimp is cooked and vegetables are tender.",
      "Garnish with fresh cilantro before serving.",
    ],
    imageBackground: require("./img/thailand.jpg")
  },
  {
    id: "14",
    videoId: "XPA3rn1XImY",
    title: "Hainanese Chicken Rice",
    image: require("./img/hainanesechickenrice.jpg"),
    ingredients: [
      "1 whole chicken",
      "2 cups jasmine rice",
      "4 cups chicken broth",
      "1 cucumber, sliced",
      "2 sprigs cilantro, chopped",
      "2 cloves garlic, minced",
      "Ginger slices",
      "Soy sauce and sesame oil for dipping sauce",
    ],
    cookingTime: 20,
    difficulty: "Intermediate",
    originCountry: "China",
    procedure: [
      "Rub chicken with salt and rinse. Boil in a pot of water with ginger until fully cooked.",
      "Cook jasmine rice in chicken broth.",
      "Mix minced garlic with soy sauce and sesame oil for dipping.",
      "Slice cooked chicken and serve on top of jasmine rice.",
      "Garnish with cucumber slices and chopped cilantro.",
      "Serve with the garlic-soy dipping sauce.",
    ],
    imageBackground: require("./img/china.jpg")
  },
  {
    id: "15",
    videoId: "psjfRM4m2Rk",
    title: "Chicken Biryani",
    image: require("./img/biryani.jpg"),
    ingredients: [
      "2 cups basmati rice, soaked",
      "1 lb chicken, cut into pieces",
      "1 cup yogurt",
      "2 onions, thinly sliced",
      "2 tomatoes, chopped",
      "1/4 cup cooking oil",
      "2 tablespoons ghee",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon turmeric",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "4 cups chicken broth",
      "Fresh cilantro and mint for garnish",
    ],
    cookingTime: 20,
    difficulty: "Advanced",
    originCountry: "India",
    procedure: [
      "Marinate chicken in yogurt, ginger-garlic paste, and spices for at least 1 hour.",
      "In a pot, sauté sliced onions until golden brown; set half aside for garnish.",
      "Add marinated chicken to the pot and cook until browned.",
      "Stir in tomatoes and cook until softened.",
      "Layer soaked rice over the chicken mixture; add ghee and fried onions.",
      "Pour chicken broth over the rice and cook until rice is tender.",
      "Garnish with fresh cilantro and mint before serving.",
    ],
    imageBackground: require("./img/india.jpg")
  },
  {
    id: "16",
    videoId: "pXA2H6l-wiA",
    title: "Dim Sum Shumai",
    image: require("./img/dimshumai.jpg"),
    ingredients: [
      "1/2 lb ground pork",
      "1/2 lb shrimp, finely chopped",
      "1/4 cup water chestnuts, minced",
      "2 tablespoons soy sauce",
      "1 tablespoon sesame oil",
      "1 tablespoon ginger, minced",
      "1 tablespoon green onion, finely chopped",
      "Wonton wrappers",
      "Soy sauce and chili oil for dipping",
    ],
    cookingTime: 20,
    difficulty: "Intermediate",
    originCountry: "China",
    procedure: [
      "In a bowl, mix ground pork, chopped shrimp, water chestnuts, soy sauce, sesame oil, ginger, and green onions.",
      "Place a spoonful of the mixture onto a wonton wrapper; gather edges and pleat the top.",
      "Steam dumplings for about 15-20 minutes until cooked.",
      "Serve with soy sauce and chili oil for dipping.",
    ],
    imageBackground: require("./img/china.jpg")
  },
  {
    id: "17",
    videoId: "9RNxC6w7ERg",
    title: "Tom Kha Gai",
    image: require("./img/tomkhagai.jpg"),
    ingredients: [
      "1 lb chicken breast, thinly sliced",
      "4 cups chicken broth",
      "1 can (14 oz) coconut milk",
      "1 lemongrass stalk, bruised",
      "3 kaffir lime leaves",
      "2 tablespoons fish sauce",
      "1 tablespoon lime juice",
      "1 tablespoon galangal, sliced",
      "1 tablespoon chili paste",
      "Mushrooms and cilantro for garnish",
    ],
    cookingTime: 15,
    originCountry: "Thailand",
    difficulty: "Advanced",
    procedure: [
      "In a pot, bring chicken broth to a simmer with lemongrass, kaffir lime leaves, and galangal.",
      "Add chicken slices and cook until they are no longer pink.",
      "Stir in coconut milk, fish sauce, lime juice, and chili paste.",
      "Simmer for an additional 10-15 minutes.",
      "Remove lemongrass and kaffir lime leaves before serving.",
      "Garnish with mushrooms and cilantro.",
    ],
    imageBackground: require("./img/thailand.jpg")
  },
  {
    id: "18",
    videoId: "PBEElC7tfr4",
    title: "Kakigōri",
    image: require("./img/kakigori.jpg"),
    ingredients: [
      "Ice cubes or shaved ice",
      "Sweetened condensed milk",
      "Flavored syrups (such as matcha, strawberry, or melon)",
      "Mochi balls, for topping (optional)",
      "Red bean paste, for topping (optional)",
      "Fresh fruits, sliced (optional)",
    ],
    cookingTime: 7,
    difficulty: "Easy",
    originCountry: "Japan",
    procedure: [
      "1. If you don't have shaved ice, you can create it by blending ice cubes in a blender until they reach a snow-like consistency.",
      "2. Pack the shaved ice into a bowl or cup, creating a mound on top.",
      "3. Drizzle sweetened condensed milk generously over the shaved ice.",
      "4. Add your desired flavored syrup(s) over the top. Common choices include matcha, strawberry, or melon syrup.",
      "5. Optionally, add toppings such as mochi balls, red bean paste, or fresh sliced fruits for extra flavor and texture.",
      "6. Serve immediately and enjoy your refreshing Kakigōri!",
    ],
    imageBackground: require("./img/japan.jpg")
  },
  {
    id: "19",
    videoId: "Y-Y9CXGRJPU",
    title: "Gimbap",
    image: require("./img/gimbap.jpg"),
    ingredients: [
      "4 sheets roasted seaweed (nori)",
      "2 cups cooked short-grain rice",
      "1/2 lb bulgogi (marinated beef), cooked and sliced",
      "1 cucumber, julienned",
      "2 carrots, julienned and sautéed",
      "2 eggs, scrambled and thinly sliced",
      "Sesame oil and sesame seeds",
      "Soy sauce for dipping",
    ],
    cookingTime: 15,
    difficulty: "Advanced",
    originCountry: "South Korea",
    procedure: [
      "Place a sheet of seaweed on a bamboo sushi rolling mat.",
      "Wet your hands and spread a thin layer of rice over the seaweed, leaving a small border at the top.",
      "Arrange bulgogi, cucumber, carrots, and scrambled eggs along the bottom edge of the rice.",
      "Roll the gimbap tightly from the bottom using the bamboo mat as a guide.",
      "Seal the edge with a bit of water.",
      "Slice the roll into bite-sized pieces.",
      "Serve with soy sauce for dipping.",
    ],
    imageBackground: require("./img/southkorea.jpg")
  },
  {
    id: "20",
    videoId: "DYIKWdO1WRY",
    title: "Thai Tub Tim Grob",
    image: require("./img/thaitubtimgrob.jpg"),
    ingredients: [
      "1 cup water chestnut cubes",
      "Red food coloring",
      "Tapioca pearls, cooked",
      "Sugar syrup",
      "Crushed ice",
      "Coconut milk",
    ],
    cookingTime: 10,
    difficulty: "Easy",
    originCountry: "Thailand",
    procedure: [
      "Color water chestnut cubes with red food coloring.",
      "Mix the colored water chestnut cubes with cooked tapioca pearls.",
      "Place the mixture over crushed ice.",
      "Pour sugar syrup and coconut milk over the top.",
      "Stir before enjoying the refreshing dessert.",
    ],
    imageBackground: require("./img/thailand.jpg")
  },
  {
    id: "21",
    videoId: "6HVDmHRHMOU",
    title: "Leche Flan",
    image: require("./img/lecheplan.jpg"),
    ingredients: [
      "10 egg yolks",
      "1 can (14 oz) sweetened condensed milk",
      "1 can (12 oz) evaporated milk",
      "1 cup sugar",
    ],
    cookingTime: 30,
    difficulty: "Intermediate",
    originCountry: "Philippines",
    procedure: [
      "In a bowl, whisk together egg yolks, sweetened condensed milk, and evaporated milk until well combined.",
      "Strain the mixture to achieve a smooth consistency.",
      "In a saucepan, caramelize sugar until golden brown.",
      "Pour the caramelized sugar into molds.",
      "Pour the egg mixture over the caramelized sugar.",
      "Steam until the leche flan is set.",
      "Allow to cool before refrigerating.",
      "Invert the mold onto a serving plate to release the leche flan with caramel on top.",
    ],
    imageBackground: require("./img/philippines.jpg")
  },
  {
    id: "22",
    videoId: "_opxqmcnKEY",
    title: "Espasol",
    image: require("./img/espasol.jpg"),
    ingredients: [
      "2 cups glutinous rice flour",
      "1 cup rice flour",
      "2 cups coconut milk",
      "1 cup sugar",
      "Grated coconut for coating",
    ],
    cookingTime: 30,
    difficulty: "Intermediate",
    originCountry: "Philippines",
    procedure: [
      "In a pan, toast glutinous rice flour and rice flour until light brown.",
      "In a separate pot, combine coconut milk and sugar; heat until the sugar is dissolved.",
      "Gradually add the toasted flour to the coconut milk mixture, stirring continuously to avoid lumps.",
      "Cook until the mixture thickens and pulls away from the sides of the pan.",
      "Allow the mixture to cool slightly.",
      "Shape the mixture into cylindrical logs and roll in grated coconut.",
      "Slice into bite-sized pieces.",
    ],
    imageBackground: require("./img/philippines.jpg")
  },
  {
    id: "23",
    videoId: "2AqwGhj_MjY",
    title: "Malaysian Apam Balik",
    image: require("./img/malaysianapambalik.jpg"),
    ingredients: [
      "1 cup all-purpose flour",
      "1/2 cup granulated sugar",
      "1/2 teaspoon baking soda",
      "1/2 teaspoon baking powder",
      "1/2 cup coconut milk",
      "1/2 cup water",
      "1 egg",
      "Corn kernels, crushed peanuts, and sugar for filling",
    ],
    cookingTime: 30,
    difficulty: "Intermediate",
    originCountry: "Malaysia",
    procedure: [
      "in a bowl, mix all-purpose flour, sugar, baking soda, and baking powder.",
      "In a separate bowl, whisk coconut milk, water, and egg.",
      "Combine the wet and dry ingredients to form a smooth batter.",
      "Remove the pancake from the pan and set it aside.",
    ],
    imageBackground: require("./img/malaysia.jpg")
  },
  {
    id: "24",
    videoId: "uxJe1cEr1Ts",
    title: "Baklava",
    image: require("./img/baklava.jpg"),
    ingredients: [
      "1 lb phyllo dough",
      "1 lb mixed nuts (walnuts, pistachios), chopped",
      "1 cup unsalted butter, melted",
      "1 cup granulated sugar",
      "1 cup water",
      "1/2 cup honey",
      "1 teaspoon lemon juice",
      "Ground cinnamon (optional)",
    ],
    cookingTime: 15,
    difficulty: "Advanced",
    originCountry: "Arabia",
    procedure: [
      "Preheat the oven to 350°F (175°C).",
      "Butter a baking dish and layer sheets of phyllo dough, brushing each layer with melted butter.",
      "Spread a layer of chopped nuts over the phyllo.",
      "Repeat the layering process until all ingredients are used, finishing with a layer of phyllo on top.",
      "Cut the baklava into diamond or square shapes before baking.",
      "Bake until golden brown.",
      "In a saucepan, combine sugar, water, honey, and lemon juice to create a syrup.",
      "Pour the syrup over the baklava while it's still hot. Optionally, sprinkle with ground cinnamon.",
    ],
    imageBackground: require("./img/arabia.jpg")
  },
  {
    id: "25",
    videoId: "n-fFtPbTGHk",
    title: "Char Kway Teow",
    image: require("./img/charkwayteow.jpg"),
    ingredients: [
      "4 oz flat rice noodles",
      "1/2 lb prawns, peeled and deveined",
      "1/2 lb Chinese sausage, sliced",
      "2 eggs, beaten",
      "2 cloves garlic, minced",
      "2 tablespoons soy sauce",
      "1 tablespoon fish sauce",
      "1 tablespoon oyster sauce",
      "1 tablespoon chili paste",
      "Bean sprouts",
      "Chinese chives, chopped",
      "Lime wedges",
    ],
    cookingTime: 20,
    difficulty: "Advanced",
    originCountry: "Singapore",
    procedure: [
      "Soak rice noodles in warm water until softened.",
      "In a wok or large pan, stir-fry prawns and Chinese sausage until cooked.",
      "Push the prawns and sausage to one side and add minced garlic to the empty side, cooking until fragrant.",
      "Add beaten eggs to the garlic side, scrambling until cooked.",
      "Mix everything in the wok, then add drained rice noodles.",
      "Pour in soy sauce, fish sauce, oyster sauce, and chili paste. Stir well.",
      "Add bean sprouts and Chinese chives, cooking until the vegetables are slightly wilted.",
      "Serve hot, with lime wedges on the side.",
    ],
  },
  {
    id: "26",
    videoId: "WlosNFMCnE4",
    title: "Pho",
    image: require("./img/pho.jpg"),
    ingredients: [
      "8 cups beef or chicken broth",
      "200g rice noodles, cooked",
      "200g beef sirloin, thinly sliced",
      "1 onion, thinly sliced",
      "1-inch ginger, sliced",
      "2 star anise",
      "1 cinnamon stick",
      "2 tablespoons fish sauce",
      "Fresh herbs (cilantro, basil, mint)",
      "Bean sprouts and lime wedges, for serving",
    ],
    cookingTime: 20,
    difficulty: "Intermediate",
    originCountry: "Vietnam",
    procedure: [
      "In a pot, simmer broth with ginger, star anise, and cinnamon for 15 minutes.",
      "Cook rice noodles according to package instructions.",
      "Arrange sliced beef and onion on top of the noodles in serving bowls.",
      "Pour hot broth over the beef and noodles. The hot broth will cook the beef slices.",
      "Season with fish sauce and garnish with fresh herbs.",
      "Serve with bean sprouts and lime wedges on the side.",
    ],
    imageBackground: require("./img/vietnam.jpg")
  },
  {
    id: "27",
    videoId: "e5cjajD6zw8",
    title: "Bún Riêu",
    image: require("./img/bunrieu.jpeg"),
    ingredients: [
      "Crab meat or crab paste",
      "Pork bones for broth",
      "Tomatoes, chopped",
      "Tofu, cubed",
      "Rice vermicelli",
      "Vietnamese herbs (perilla, mint)",
      "Shrimp paste and fish sauce for seasoning",
    ],
    cookingTime: 20,
    difficulty: "Easy",
    originCountry: "vietnam",
    procedure: [
      "1. In a pot, combine beef broth, star anise, cinnamon stick, and ginger. Simmer for 1-2 hours.",
      "2. Cook rice noodles according to package instructions. Drain and set aside.",
      "3. In serving bowls, place a handful of rice noodles, raw beef slices, and onion slices.",
      "4. Pour hot broth over the noodles and beef. The hot broth will cook the beef slices.",
      "5. Add fish sauce and soy sauce to taste. Garnish with bean sprouts, basil, and lime wedges.",
    ],
  },
  {
    id: "29",
    videoId: "EApkyOBewEw",
    title: "Chinese Hot Pot",
    image: require("./img/hotpot.jpeg"),
    ingredients: [
      "Broth (chicken, beef, or vegetable)",
      "Thinly sliced meat (beef, lamb, pork, or chicken)",
      "Assorted vegetables (bok choy, napa cabbage, mushrooms, tofu, etc.)",
      "Dipping sauces (soy sauce, sesame oil, hoisin sauce, chopped green onions, etc.)",
      "Noodles (optional)",
    ],
    cookingTime: 40,
    difficulty: "Advanced",
    originCountry: "China",
    procedure: [
      "1. Prepare the broth of your choice. You can use store-bought hot pot broth or make your own by simmering ingredients like bones, aromatics, and seasonings in water.",
      "2. Set up the hot pot on a portable stove in the center of the dining table.",
      "3. Arrange thinly sliced meat, assorted vegetables, and other desired ingredients on plates for easy access.",
      "4. Bring the broth to a simmer in the hot pot. Place some ingredients into the pot to cook. Cooking times vary depending on the ingredient, so adjust accordingly.",
      "5. Each diner uses chopsticks or a strainer to cook their chosen ingredients in the hot broth. Once cooked, dip in the desired sauce before eating.",
      "6. Add more ingredients to the pot as needed, and continue the cooking and dining process.",
      "7. Optional: Towards the end, you can add noodles to the hot pot to cook.",
      "8. Once you've enjoyed all your ingredients, you can finish the meal by drinking the flavorful broth.",
      "9. Enjoy your interactive and delicious Chinese Hot Pot experience!",
    ],
    imageBackground: require("./img/china.jpg")
  },
  {
    id: "30",
    videoId: "mlngdPqXi10",
    title: "Amok Trey",
    image: require("./img/amoktrey.jpeg"),
    ingredients: [
      "1 lb white fish fillets, cut into chunks",
      "1 can (14 oz) coconut milk",
      "2 tablespoons fish sauce",
      "1 tablespoon red curry paste",
      "1 tablespoon sugar",
      "1 egg",
      "Kaffir lime leaves for garnish",
      "Banana leaves for steaming",
    ],
    cookingTime: 20,
    difficulty: "Intermediate",
    originCountry: "Cambodia",
    procedure: [
      "1. In a bowl, mix coconut milk, fish sauce, red curry paste, and sugar.",
      "2. Beat the egg and add it to the mixture, stirring until well combined.",
      "3. Place fish chunks in the mixture and marinate for 20 minutes.",
      "4. Cut banana leaves into squares and use them to create cups. Pour the fish mixture into the cups.",
      "5. Steam the cups for about 20-25 minutes until the fish is cooked.",
      "6. Garnish with kaffir lime leaves and serve with steamed rice.",
    ],
    imageBackground: require("./img/cambodia.jpg")
  },
];
