export const DATA = [
    // 1st Country
    {
      id: "1",
      videoId: "wwapBsT0oc8",
      title: "Adobo",
      image: require("./img/adobo.jpeg"),
      ingredients: [
        "2 tablespoons vegetable oil",
        "1 (3 pound) chicken, cut into pieces",
        "1 large onion, quartered and sliced",
        "2 tablespoons minced garlic",
        "⅔ cup low sodium soy sauce",
        "⅓ cup white vinegar",
        "1 tablespoon garlic powder",
        "2 teaspoons black pepper",
        "1 bay leaf",
      ],
      cookingTime: 65,
      originCountry: "Philippines",
      procedure: [
        "1. Heat vegetable oil in a large skillet over medium-high heat. Cook chicken pieces until golden brown, 2 to 3 minutes per side. Transfer chicken to a plate and set aside.",
        "2. Add onion and garlic to the skillet; cook until softened and brown, about 6 minutes.",
        "3. Pour in soy sauce and vinegar and season with garlic powder, black pepper, and bay leaf",
        "4. Return chicken to pan, increase heat to high, and bring to a boil. Reduce heat to medium-low, cover, and simmer until chicken is tender and cooked through, 35 to 40 minutes.",
      ],
    },
  
    {
      id: "2",
      videoId: "CzBF1IhIn1M",
      title: "Sinigang",
      image: require("./img/sinigang.jpeg"),
      ingredients: [
        "1 lb pork ribs",
        "1 eggplant",
        "1 radish",
        "1 green pepper",
        "4 cups water",
        "1 packet sinigang mix",
      ],
      cookingTime: 60,
      originCountry: "Philippines",
      procedure: [
        "1. In a large pot, add water and bring to a boil.",
        "2. Add pork ribs and cook until tender.",
        "3. Add vegetables and sinigang mix. Simmer until vegetables are cooked.",
      ],
    },
    {
      id: "3",
      videoId: "M-Gso2xK9t8",
      title: "Sisig",
      image: require("./img/sisig.jpeg"),
      ingredients: [
        "1 lb pig ears",
        "1 onion",
        "1 red chili pepper",
        "2 tbsp soy sauce",
        "2 tbsp calamansi juice",
      ],
      cookingTime: 45,
      originCountry: "Philippines",
      procedure: [
        "1. Boil pig ears until tender, then grill until crispy.",
        "2. Chop pig ears into small pieces.",
        "3. Sauté chopped pig ears with onions, chili pepper, soy sauce, and calamansi juice.",
      ],
    },
    {
      id: "4",
      videoId: "KnJ3abXjgME",
      title: "Peking Duck",
      image: require("./img/pekingduck.jpeg"),
      ingredients: [
        "1 whole duck",
        "5-spice powder",
        "Salt",
        "Maltose syrup",
        "Cucumber",
        "Pancakes",
      ],
      cookingTime: 120,
      originCountry: "China",
      procedure: [
        "1. Clean and season the duck with 5-spice powder and salt.",
        "2. Air-dry the duck for several hours.",
        "3. Roast the duck, basting with maltose syrup until crispy.",
        "4. Serve with pancakes and sliced cucumber.",
      ],
    },
    {
      id: "5",
      videoId: "mQufT9XjimY",
      title: "Kung Pao Chicken",
      image: require("./img/kungpaochicken.jpeg"),
      ingredients: [
        "1 lb chicken breast",
        "1/2 cup peanuts",
        "3 cloves garlic",
        "3 dried red chili peppers",
      ],
      cookingTime: 30,
      originCountry: "China",
      procedure: [
        "1. Cut chicken into small cubes and marinate with soy sauce and cornstarch.",
        "2. Stir-fry chicken in a hot wok until cooked. Remove and set aside.",
        "3. In the same wok, stir-fry garlic and dried chili peppers.",
        "4. Add peanuts and cooked chicken. Stir-fry with sauce.",
      ],
    },
    {
      id: "6",
      videoId: "34Ax3BmGtY0",
      title: "Dumplings",
      image: require("./img/dumpling.jpeg"),
      ingredients: [
        "1 lb ground pork",
        "Napa cabbage",
        "Green onions",
        "Ginger",
        "Wonton wrappers",
      ],
      cookingTime: 45,
      originCountry: "China",
      procedure: [
        "1. Mix ground pork, finely chopped cabbage, green onions, and ginger.",
        "2. Place a spoonful of filling on a wonton wrapper. Seal and shape the dumplings.",
        "3. Boil or steam dumplings until cooked. Serve with dipping sauce.",
      ],
    },
    {
      id: "7",
      videoId: "TgoN7bsTFmU",
      title: "Sashimi",
      image: require("./img/sashimi.jpeg"),
      ingredients: [
        "Fresh raw fish (e.g., salmon, tuna)",
        "Soy sauce",
        "Wasabi",
        "Pickled ginger",
      ],
      cookingTime: 15,
      originCountry: "Japan",
      procedure: [
        "1. Slice fresh raw fish into thin pieces.",
        "2. Serve with soy sauce, wasabi, and pickled ginger.",
      ],
    },
    {
      id: "8",
      videoId: "l8BCDXkwHwI",
      title: "Soba",
      image: require("./img/soba.jpeg"),
      ingredients: [
        "Soba noodles",
        "Soy sauce",
        "Mirin",
        "Dashi broth",
        "Scallions",
        "Wasabi",
      ],
      cookingTime: 20,
      originCountry: "Japan",
      procedure: [
        "1. Cook soba noodles until al dente, then rinse with cold water.",
        "2. Serve with a dipping sauce made from soy sauce, mirin, and dashi broth.",
        "3. Garnish with scallions and wasabi.",
      ],
    },
    {
      id: "9",
      videoId: "joweUxpHaqc",
      title: "Sushi",
      image: require("./img/sushi.jpeg"),
      ingredients: [
        "Sushi rice",
        "Fresh fish (e.g., salmon, tuna)",
        "Nori seaweed",
        "Cucumber",
        "Avocado",
      ],
      cookingTime: 30,
      originCountry: "Japan",
      procedure: [
        "1. Prepare sushi rice and let it cool.",
        "2. Lay out a sheet of nori, add a layer of rice, and top with fish, cucumber, and avocado",
      ],
    },
  ],
  {
    id: "10",
    videoId: "uggcCFhgUSQ",
    title: "Pad thai",
    image: require("./img/pad-thai.jpeg"),
    ingredients: [
      "8 oz rice noodles",
      "2 tablespoons vegetable oil",
      "1 cup firm tofu, cubed",
      "2 cloves garlic, minced",
      "1/2 cup peanuts, chopped",
      "1 cup bean sprouts",
      "2 green onions, chopped",
      "2 eggs, lightly beaten",
      "1 lime, cut into wedges",
      "1/4 cup chopped cilantro",
      "1/4 cup chopped fresh basil",
      "2 tablespoons fish sauce",
      "2 tablespoons soy sauce",
      "1 tablespoon tamarind paste",
      "1 tablespoon sugar",
    ],
    cookingTime: "10 minutes",
    originCountry: "Thailand",
    procedure: [
      "1. Cook rice noodles according to package instructions; drain and set aside.",
      "2. In a wok or large skillet, heat vegetable oil over medium-high heat.",
      "3. Add tofu and cook until golden brown. Remove from the wok and set aside.",
      "4. In the same wok, add minced garlic and cook until fragrant.",
      "5. Push garlic to one side and pour beaten eggs into the other side. Scramble eggs until just set.",
      "6. Add cooked noodles, tofu, fish sauce, soy sauce, tamarind paste, and sugar to the wok. Toss everything together.",
      "7. Stir in half of the chopped peanuts, bean sprouts, and green onions. Cook for an additional 2-3 minutes.",
      "8. Serve Pad Thai on a platter, garnished with remaining peanuts, chopped cilantro, fresh basil, and lime wedges.",
    ],
    }
  [,
  {
    id: "11",
    videoId: "qlKUHFmLsLo",
    title: "Kimchi Fried Rice",
    image: require("./img/kimchirice.jpg"),
    ingredients: [
      "cups cooked rice, chilled",
      "1 cup kimchi, chopped",
      "1/2 cup kimchi juice",
      "1 cup cooked and shredded chicken or pork",
      "1 carrot, diced",
      "1 cup frozen peas",
      "2 eggs, beaten",
      "3 green onions, sliced",
      "2 tablespoons soy sauce",
      "1 tablespoon sesame oil",
    ],
    cookingTime: "15 minutes",
    originCountry: "South Korea",
    procedure: [
      "Heat a large skillet or wok over medium heat.",
      "Add diced carrots and cook until slightly softened.",
      "Add kimchi and shredded chicken/pork to the skillet; stir-fry for a few minutes.",
      "Push the ingredients to one side of the skillet; pour beaten eggs into the other side. Scramble eggs until cooked.",
      "Mix everything in the skillet together.",
      "Add chilled rice, kimchi juice, frozen peas, soy sauce, and sesame oil. Stir-fry until well combined and heated through.",
      "Garnish with sliced green onions before serving.",
    ],
  },
  {
    id: "12",
    videoId: "TLl8n5WJJfI",
    title: "Tom Yum Soup",
    image: require("./img/TomYumSoup.jpeg"),
    ingredients: [
      "4 cups chicken broth",
      "1 stalk lemongrass, sliced",
      "3 kaffir lime leaves",
      "200g shrimp, peeled and deveined",
      "200g mushrooms, sliced",
      "1 medium tomato, cut into wedges",
      "1 small onion, sliced",
      "2 tablespoons fish sauce",
      "1 tablespoon lime juice",
      "1 teaspoon chili paste",
      "Fresh cilantro for garnish",
    ],
    cookingTime: "10 minutes",
    originCountry: "Thailand",
    procedure: [
      "In a pot, bring chicken broth to a boil. Add lemongrass and kaffir lime leaves.",
      "Add shrimp, mushrooms, tomato, and onion to the pot.",
      "Season with fish sauce, lime juice, and chili paste.",
      "Simmer until shrimp is cooked and vegetables are tender.",
      "Garnish with fresh cilantro before serving.",
    ],
  },
  ];
  [,
  {
  id: "14",
      videoId: "XPA3rn1XImY",
      title: "Hainanese Chicken Rice",
      image: require("./img/hainanesechickenrice.jpeg"),
      ingredients: [
     "1 whole chicken",
     "2 cups jasmine rice",
     "4 cups chicken broth",
     "1 cucumber, sliced",
     "2 sprigs cilantro, chopped",
     "2 cloves garlic, minced",
     "Ginger slices",
     "Soy sauce and sesame oil for dipping sauce",
      ],
      cookingTime: "20 minutes",
      originCountry: "China",
      procedure: [
        "Rub chicken with salt and rinse. Boil in a pot of water with ginger until fully cooked.",
        "Cook jasmine rice in chicken broth.",
        "Mix minced garlic with soy sauce and sesame oil for dipping.",
        "Slice cooked chicken and serve on top of jasmine rice.",
        "Garnish with cucumber slices and chopped cilantro.",
        "Serve with the garlic-soy dipping sauce.",
      ],
    },
    [,
  {
    id: "15",
        videoId: "psjfRM4m2Rk",
        title: "Biryani",
        image: require("./img/biryani.jpeg"),
        ingredients: [
       "2 cups basmati rice, soaked",
       "1 lb chicken, cut into pieces",
       "1 cup yogurt",
       "2 onions, thinly sliced",
       "2 tomatoes, chopped",
       "1/4 cup cooking oil",
       "2 tablespoons ghee",
       "1 tablespoon ginger-garlic paste",
       "1 teaspoon turmeric",
        "1 teaspoon cumin powder",
       "1 teaspoon coriander powder",
       "1 teaspoon garam masala",
       "4 cups chicken broth",
       "Fresh cilantro and mint for garnish",
        ],
        cookingTime: "20 minutes",
        originCountry: "india",
        procedure: [
      "Marinate chicken in yogurt, ginger-garlic paste, and spices for at least 1 hour.",
      "In a pot, sauté sliced onions until golden brown; set half aside for garnish.",
      "Add marinated chicken to the pot and cook until browned.",
      "Stir in tomatoes and cook until softened.",
      "Layer soaked rice over the chicken mixture; add ghee and fried onions.",
      "Pour chicken broth over the rice and cook until rice is tender.",
       "Garnish with fresh cilantro and mint before serving.",
        ],
      },
    ],
    {
    id: "16",
        videoId: "pXA2H6l-wiA",
        title: "Dim Sum Shumai",
        image: require("./img/dimshumai.jpeg"),
        ingredients: [
        "1/2 lb ground pork",
        "1/2 lb shrimp, finely chopped",
        "1/4 cup water chestnuts, minced",
        "2 tablespoons soy sauce",
        "1 tablespoon sesame oil",
        "1 tablespoon ginger, minced",
        "1 tablespoon green onion, finely chopped",
        "Wonton wrappers",
        "Soy sauce and chili oil for dipping",
        ],
        cookingTime: "20 minutes",
        originCountry: "China",
        procedure: [
          "In a bowl, mix ground pork, chopped shrimp, water chestnuts, soy sauce, sesame oil, ginger, and green onions.",
          "Place a spoonful of the mixture onto a wonton wrapper; gather edges and pleat the top.",
          "Steam dumplings for about 15-20 minutes until cooked.",
          "Serve with soy sauce and chili oil for dipping.",
        ],
    },
    [,
    {
    id: "17",
        videoId: "9RNxC6w7ERg",
        title: "Tom Kha Gai",
        image: require("./img/tomkhagai.jpeg"),
        ingredients: [
        "1 lb chicken breast, thinly sliced",
        "4 cups chicken broth",
        "1 can (14 oz) coconut milk",
        "1 lemongrass stalk, bruised",
        "3 kaffir lime leaves",
        "2 tablespoons fish sauce",
        "1 tablespoon lime juice",
        "1 tablespoon galangal, sliced",
        "1 tablespoon chili paste",
        "Mushrooms and cilantro for garnish",
        ],
        cookingTime: "",
        originCountry: "Thailand",
        procedure: [
          "In a pot, bring chicken broth to a simmer with lemongrass, kaffir lime leaves, and galangal.",
          "Add chicken slices and cook until they are no longer pink.",
          "Stir in coconut milk, fish sauce, lime juice, and chili paste.",
          "Simmer for an additional 10-15 minutes.",
          "Remove lemongrass and kaffir lime leaves before serving.",
          "Garnish with mushrooms and cilantro.",
        ],
      },
    ],
    [,
  {
    id: "18",
    videoId: "",
    title: "Peking Duck",
    image: require("./img/pekingduck.jpeg"),
    ingredients: [
      "1 whole duck",
      "1/4 cup hoisin sauce",
      "1/4 cup soy sauce",
      "1/4 cup honey",
      "2 tablespoons Chinese five-spice powder",
      "1 cucumber, julienned",
      "Hoisin sauce for serving",
      "Thin pancakes or steamed buns",
    ],
    cookingTime: "3 hours",
    originCountry: "China",
    procedure: [
      "Mix hoisin sauce, soy sauce, honey, and Chinese five-spice powder to create the marinade.",
      "Rub the duck inside and out with the marinade and let it marinate in the refrigerator for at least 2 hours.",
      "Preheat the oven to 350°F (175°C) and roast the duck for about 2.5-3 hours.",
      "Slice the roasted duck and serve with julienned cucumber, hoisin sauce, and thin pancakes or steamed buns.",
    ],
  },
  {
  id: "19",
  videoId: "Y-Y9CXGRJPU",
  title: "Gimbap",
  image: require("./img/gimbap.jpeg"),
  ingredients: [
    "4 sheets roasted seaweed (nori)",
  "2 cups cooked short-grain rice",
  "1/2 lb bulgogi (marinated beef), cooked and sliced",
  "1 cucumber, julienned",
  "2 carrots, julienned and sautéed",
  "2 eggs, scrambled and thinly sliced",
  "Sesame oil and sesame seeds",
  "Soy sauce for dipping",
  ],
  cookingTime: "15 Minutes",
  originCountry: "South Korea",
  procedure: [
  "Place a sheet of seaweed on a bamboo sushi rolling mat.",
  "Wet your hands and spread a thin layer of rice over the seaweed, leaving a small border at the top.",
  "Arrange bulgogi, cucumber, carrots, and scrambled eggs along the bottom edge of the rice.",
  "Roll the gimbap tightly from the bottom using the bamboo mat as a guide.",
  "Seal the edge with a bit of water.",
  "Slice the roll into bite-sized pieces.",
  "Serve with soy sauce for dipping.",
  ],
  },
  {
    id: "20",
    videoId: "DYIKWdO1WRY",
    title: "Thai Tub Tim Grob",
    image: require("./img/thaitubtimgrob.jpeg"),
    ingredients: [
      "1 cup water chestnut cubes",
      "Red food coloring",
      "Tapioca pearls, cooked",
      "Sugar syrup",
      "Crushed ice",
      "Coconut milk",
    ],
    cookingTime: "10 minutes",
    originCountry: "Thailand",
    procedure: [
      "Color water chestnut cubes with red food coloring.",
      "Mix the colored water chestnut cubes with cooked tapioca pearls.",
      "Place the mixture over crushed ice.",
      "Pour sugar syrup and coconut milk over the top.",
      "Stir before enjoying the refreshing dessert.",
    ],
  },
  ],
  {
  id: "21",
      videoId: "",
      title: "Leche Flan",
      image: require("./img/lecheplan.jpeg"),
      ingredients: [
      "10 egg yolks",
      "1 can (14 oz) sweetened condensed milk",
      "1 can (12 oz) evaporated milk",
      "1 cup sugar",
      ],
      cookingTime: "30 minutes",
      originCountry: "Philippines",
      procedure: [
      "In a bowl, whisk together egg yolks, sweetened condensed milk, and evaporated milk until well combined.",
      "Strain the mixture to achieve a smooth consistency.",
      "In a saucepan, caramelize sugar until golden brown.",
      "Pour the caramelized sugar into molds.",
      "Pour the egg mixture over the caramelized sugar.",
      "Steam until the leche flan is set.",
      "Allow to cool before refrigerating.",
      "Invert the mold onto a serving plate to release the leche flan with caramel on top.",
      ],
    },
  ];
  [,
  {
  id: "22",
      videoId: "",
      title: "Espasol",
      image: require("./img/espasol.jpeg"),
      ingredients:  [
        "2 cups glutinous rice flour",
        "1 cup rice flour",
        "2 cups coconut milk",
        "1 cup sugar",
        "Grated coconut for coating",
        ],
      cookingTime: "30 minutes",
      originCountry: "Philippines",
      procedure: [
        "In a pan, toast glutinous rice flour and rice flour until light brown.",
         "In a separate pot, combine coconut milk and sugar; heat until the sugar is dissolved.",
         "Gradually add the toasted flour to the coconut milk mixture, stirring continuously to avoid lumps.",
         "Cook until the mixture thickens and pulls away from the sides of the pan.",
         "Allow the mixture to cool slightly.",
         "Shape the mixture into cylindrical logs and roll in grated coconut.",
         "Slice into bite-sized pieces.",
       ],
    },
  ],
  {
  id: "23",
      videoId: "",
      title: "Malaysian Apam Balik",
      image: require("./img/malaysianapambalik .jpeg"),
      ingredients: [
      "1 cup all-purpose flour",
      "1/2 cup granulated sugar",
      "1/2 teaspoon baking soda",
      "1/2 teaspoon baking powder",
      "1/2 cup coconut milk",
      "1/2 cup water",
      "1 egg",
      "Corn kernels, crushed peanuts, and sugar for filling",
      ],
      cookingTime: "30 minutes",
      originCountry: "Malaysia",
      procedure: [
      "in a bowl, mix all-purpose flour, sugar, baking soda, and baking powder.",
      "In a separate bowl, whisk coconut milk, water, and egg.",
      "Combine the wet and dry ingredients to form a smooth batter.",
      "Remove the pancake from the pan and set it aside.",
      ],
    },
  [,
  {
      id: "24",
      videoId: "TLl8n5WJJfI",
      title: "Baklava",
      image: require("./img/baklava.jpeg"),
      ingredients: [
      "1 lb phyllo dough",
      "1 lb mixed nuts (walnuts, pistachios), chopped",
      "1 cup unsalted butter, melted",
      "1 cup granulated sugar",
      "1 cup water",
      "1/2 cup honey",
      "1 teaspoon lemon juice",
      "Ground cinnamon (optional)",
      ],
      cookingTime: "35 minutes",
      originCountry: "Arabia",
      procedure: [
        "Preheat the oven to 350°F (175°C).",
      "Butter a baking dish and layer sheets of phyllo dough, brushing each layer with melted butter.",
      "Spread a layer of chopped nuts over the phyllo.",
      "Repeat the layering process until all ingredients are used, finishing with a layer of phyllo on top.",
      "Cut the baklava into diamond or square shapes before baking.",
      "Bake until golden brown.",
      "In a saucepan, combine sugar, water, honey, and lemon juice to create a syrup.",
      "Pour the syrup over the baklava while it's still hot. Optionally, sprinkle with ground cinnamon.",
      ],
    },
    ],
  [,
  {
  id: "25",
      videoId: "",
      title: "Char Kway Teow",
      image: require("./img/charkwayteow.jpeg"),
      ingredients: [
      "4 oz flat rice noodles",
      "1/2 lb prawns, peeled and deveined",
      "1/2 lb Chinese sausage, sliced",
      "2 eggs, beaten",
      "2 cloves garlic, minced",
      "2 tablespoons soy sauce",
      "1 tablespoon fish sauce",
      "1 tablespoon oyster sauce",
      "1 tablespoon chili paste",
      "Bean sprouts",
      "Chinese chives, chopped",
      "Lime wedges",
      ],
      cookingTime: "20 minutes",
      originCountry: "Singapore",
      procedure: [
      "Soak rice noodles in warm water until softened.",
      "In a wok or large pan, stir-fry prawns and Chinese sausage until cooked.",
      "Push the prawns and sausage to one side and add minced garlic to the empty side, cooking until fragrant.",
      "Add beaten eggs to the garlic side, scrambling until cooked.",
      "Mix everything in the wok, then add drained rice noodles.",
      "Pour in soy sauce, fish sauce, oyster sauce, and chili paste. Stir well.",
      "Add bean sprouts and Chinese chives, cooking until the vegetables are slightly wilted.",
      "Serve hot, with lime wedges on the side.",
      ],
    },
  ],
    [,
    {
      id: "26",
      videoId: "",
      title: "Pho",
      image: require("./img/pho.jpeg"),
      ingredients: [
      "8 cups beef or chicken broth",
      "200g rice noodles, cooked",
     "200g beef sirloin, thinly sliced",
     "1 onion, thinly sliced",
     "1-inch ginger, sliced",
     "2 star anise",
    "1 cinnamon stick",
    "2 tablespoons fish sauce",
    "Fresh herbs (cilantro, basil, mint)",
    "Bean sprouts and lime wedges, for serving",
      ],
      cookingTime: "20 minutes",
      originCountry: "Vietnam",
      procedure: [
      "In a pot, simmer broth with ginger, star anise, and cinnamon for 15 minutes.",
      "Cook rice noodles according to package instructions.",
      "Arrange sliced beef and onion on top of the noodles in serving bowls.",
      "Pour hot broth over the beef and noodles. The hot broth will cook the beef slices.",
      "Season with fish sauce and garnish with fresh herbs.",
      "Serve with bean sprouts and lime wedges on the side.",
      ],
    },
    ],
  [,
    {
      id: "27",
      videoId: "",
      title: "Bún Riêu",
      image: require("./img/bunrieu.jpeg"),
      ingredients: [
      "Crab meat or crab paste",
      "Pork bones for broth",
      "Tomatoes, chopped",
      "Tofu, cubed",
      "Rice vermicelli",
      "Vietnamese herbs (perilla, mint)",
      "Shrimp paste and fish sauce for seasoning",
      ],
      cookingTime: "20 minutes",
      originCountry: "vietnam",
      procedure: [
        "1. In a pot, combine beef broth, star anise, cinnamon stick, and ginger. Simmer for 1-2 hours.",
        "2. Cook rice noodles according to package instructions. Drain and set aside.",
        "3. In serving bowls, place a handful of rice noodles, raw beef slices, and onion slices.",
        "4. Pour hot broth over the noodles and beef. The hot broth will cook the beef slices.",
        "5. Add fish sauce and soy sauce to taste. Garnish with bean sprouts, basil, and lime wedges.",
      ],
    },
    ],
  [,
    {
      id: "28",
      videoId: "",
      title: "Bún Riêu",
      image: require("./img/bunrieu.jpeg"),
      ingredients: [
      "Crab meat or crab paste",
      "Pork bones for broth",
      "Tomatoes, chopped",
      "Tofu, cubed",
      "Rice vermicelli",
      "Vietnamese herbs (perilla, mint)",
      "Shrimp paste and fish sauce for seasoning",
      ],
      cookingTime: "20 minutes",
      originCountry: "vietnam",
      procedure: [
      "Boil pork bones to make broth. Add crab meat or paste, tomatoes, and tofu.",
      "Season with shrimp paste and fish sauce.",
      "Serve over cooked rice vermicelli, garnished with Vietnamese herbs.",
      ],
    },
    ],
  [,
  {
    id: "29",
    videoId: "",
    title: "Kung pao chicken",
    image: require("./img/kungpaochicken.jpeg"),
    ingredients: [
      "1 lb boneless, skinless chicken thighs, cut into bite-sized pieces",
      "1/2 cup unsalted dry roasted peanuts",
      "1 red bell pepper, diced",
      "1 green bell pepper, diced",
      "2 tablespoons vegetable oil",
      "3 cloves garlic, minced",
      "1 teaspoon ginger, minced",
      "2 tablespoons soy sauce",
      "1 tablespoon rice vinegar",
      "1 tablespoon hoisin sauce",
      "1 tablespoon sugar",
      "1 teaspoon cornstarch, dissolved in 2 tablespoons water",
      "4-6 dried red chilies",
      "3 green onions, sliced",
      "Cooked white rice for serving"
    ],
    cookingTime: "30 minutes",
    originCountry: "China",
    procedure: [
      "1. In a bowl, mix the soy sauce, rice vinegar, hoisin sauce, and sugar. Set aside.",
      "2. Heat vegetable oil in a wok or large skillet over medium-high heat.",
      "3. Add chicken pieces and stir-fry until browned and cooked through. Remove chicken from the wok.",
      "4. In the same wok, add more oil if needed and sauté garlic, ginger, and dried red chilies until fragrant.",
      "5. Add diced bell peppers and stir-fry for 2-3 minutes.",
      "6. Return the cooked chicken to the wok and add the soy sauce mixture. Stir well to coat.",
      "7. Add the dissolved cornstarch and continue stirring until the sauce thickens.",
      "8. Stir in peanuts and green onions.",
      "9. Serve the Kung Pao Chicken over cooked white rice.",
      "10. Garnish with additional green onions and peanuts if desired. Enjoy!"
    ],
  }
  ],
  [,
    {
      id: "30",
      videoId: "",
      title: "Amok Trey",
      image: require("./img/amoktrey.jpeg"),
      ingredients: [
        "1 lb white fish fillets, cut into chunks",
        "1 can (14 oz) coconut milk",
        "2 tablespoons fish sauce",
        "1 tablespoon red curry paste",
        "1 tablespoon sugar",
        "1 egg",
        "Kaffir lime leaves for garnish",
        "Banana leaves for steaming"
      ],
      cookingTime: "20 minutes",
      originCountry: "Cambodia",
      procedure: [
        "1. In a bowl, mix coconut milk, fish sauce, red curry paste, and sugar.",
        "2. Beat the egg and add it to the mixture, stirring until well combined.",
        "3. Place fish chunks in the mixture and marinate for 20 minutes.",
        "4. Cut banana leaves into squares and use them to create cups. Pour the fish mixture into the cups.",
        "5. Steam the cups for about 20-25 minutes until the fish is cooked.",
        "6. Garnish with kaffir lime leaves and serve with steamed rice."
      ],
    }
  ]